# Generated by Django 4.1.6 on 2023-02-01 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('A pagar', 'A Paga'), ('A receber', 'A Receber')], max_length=40)),
                ('vencimento', models.DateField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='propriedades.propriedade')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='reservas.reserva')),
            ],
        ),
    ]
