# Generated by Django 4.1.6 on 2023-02-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
        ('contas', '0003_alter_conta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedade', to='propriedades.propriedade'),
        ),
    ]
