# Generated by Django 4.1.6 on 2023-02-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_aluguel_com_imposto_and_more'),
        ('contas', '0004_alter_conta_propriedade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='reservas.reserva'),
        ),
    ]
