# Generated by Django 4.1.6 on 2023-02-01 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.SmallIntegerField()),
                ('data', models.DateField()),
                ('data_de_checkin', models.DateField()),
                ('data_de_checkout', models.DateField()),
                ('aluguel_com_imposto', models.SmallIntegerField()),
                ('aluguel_sem_imposto', models.SmallIntegerField()),
                ('imposto_do_aluguel', models.SmallIntegerField()),
                ('extras_com_imposto', models.SmallIntegerField()),
                ('extras_sem_imposto', models.SmallIntegerField()),
                ('imposto_dos_extras', models.SmallIntegerField()),
                ('total_da_reserva_com_imposto', models.SmallIntegerField()),
                ('total_da_reserva_sem_imposto', models.SmallIntegerField()),
                ('total_imposto', models.SmallIntegerField()),
                ('pagamento', models.SmallIntegerField()),
                ('pendente', models.SmallIntegerField()),
                ('nome_alojamento', models.SmallIntegerField()),
                ('localidade', models.SmallIntegerField()),
                ('portal', models.CharField(max_length=40)),
                ('comissao_calculada', models.SmallIntegerField()),
                ('comissao_personalizada', models.SmallIntegerField()),
            ],
        ),
    ]
