# Generated by Django 4.1.6 on 2023-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='aluguel_com_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='aluguel_sem_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comissao_calculada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comissao_personalizada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='extras_com_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='extras_sem_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='imposto_do_aluguel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='imposto_dos_extras',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='localidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pagamento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pendente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_da_reserva_com_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_da_reserva_sem_imposto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_imposto',
            field=models.FloatField(),
        ),
    ]
