# Generated by Django 4.1.6 on 2023-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_aluguel_com_imposto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='localidade',
            field=models.CharField(max_length=40),
        ),
    ]
