# Generated by Django 4.1.6 on 2023-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_aluguel_com_imposto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='aluguel_com_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='aluguel_sem_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comissao_calculada',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comissao_personalizada',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='extras_com_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='extras_sem_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='imposto_do_aluguel',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='imposto_dos_extras',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pagamento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pendente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_da_reserva_com_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_da_reserva_sem_imposto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_imposto',
            field=models.CharField(max_length=40),
        ),
    ]
